// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUQiaAP7YlEaM6V1NgjEsE8DJR14u2nHw',
    appId: '1:1033205193749:web:a0c752f5976067e060021c',
    messagingSenderId: '1033205193749',
    projectId: 'flutter-notificationproyect',
    authDomain: 'flutter-notificationproyect.firebaseapp.com',
    storageBucket: 'flutter-notificationproyect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKdePsu_RsITkfXbHxWTLU7y4clz4dhs',
    appId: '1:1033205193749:android:3b3da6bd1ea69a2160021c',
    messagingSenderId: '1033205193749',
    projectId: 'flutter-notificationproyect',
    storageBucket: 'flutter-notificationproyect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnxpGngfYuJ5lWQRb96mvLaYDiMC0YtAU',
    appId: '1:1033205193749:ios:7c72e1782a9af08560021c',
    messagingSenderId: '1033205193749',
    projectId: 'flutter-notificationproyect',
    storageBucket: 'flutter-notificationproyect.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnxpGngfYuJ5lWQRb96mvLaYDiMC0YtAU',
    appId: '1:1033205193749:ios:7c72e1782a9af08560021c',
    messagingSenderId: '1033205193749',
    projectId: 'flutter-notificationproyect',
    storageBucket: 'flutter-notificationproyect.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUQiaAP7YlEaM6V1NgjEsE8DJR14u2nHw',
    appId: '1:1033205193749:web:458ba21d181cda0d60021c',
    messagingSenderId: '1033205193749',
    projectId: 'flutter-notificationproyect',
    authDomain: 'flutter-notificationproyect.firebaseapp.com',
    storageBucket: 'flutter-notificationproyect.firebasestorage.app',
  );
}
